# Generated by Django 5.0.6 on 2026-05-04 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="followup",
            options={"ordering": ["scheduled_date", "priority"]},
        ),
        migrations.AddField(
            model_name="followup",
            name="auto_generated",
            field=models.BooleanField(
                default=False, help_text="Whether this was auto-generated"
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="followup_type",
            field=models.CharField(
                choices=[
                    ("call", "Phone Call"),
                    ("whatsapp", "WhatsApp Message"),
                    ("email", "Email"),
                    ("visit", "Visit"),
                    ("sms", "SMS"),
                    ("auto", "Auto-generated"),
                ],
                default="call",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="next_action",
            field=models.TextField(blank=True, help_text="Next steps identified"),
        ),
        migrations.AddField(
            model_name="followup",
            name="outcome",
            field=models.CharField(
                blank=True, help_text="Result of the follow-up", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, help_text="Whether reminder notification was sent"
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="scheduled_time",
            field=models.TimeField(
                blank=True, help_text="Specific time for the follow-up", null=True
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["lead", "status", "scheduled_date"],
                name="leads_follo_lead_id_5bd546_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="leads_follo_status_dd37a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["priority", "scheduled_date"],
                name="leads_follo_priorit_abf066_idx",
            ),
        ),
    ]
