# Generated by Django 5.0.6 on 2026-05-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_alter_company_options_alter_segment_options"),
        ("leads", "0002_alter_followup_options_followup_auto_generated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=15, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("not_specified", "Not Specified"),
                        ],
                        default="not_specified",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("total_purchases", models.IntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("last_purchase_date", models.DateTimeField(blank=True, null=True)),
                (
                    "avg_ticket_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("total_calls", models.IntegerField(default=0)),
                ("total_visits", models.IntegerField(default=0)),
                ("total_whatsapp", models.IntegerField(default=0)),
                ("last_contact_date", models.DateTimeField(blank=True, null=True)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        help_text="Display string for budget range",
                        max_length=100,
                    ),
                ),
                (
                    "occasions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {type, date} objects",
                    ),
                ),
                (
                    "timeline",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Chronological list of all interactions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_segments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interested_customers",
                        to="branches.segment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leads.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="leads_custo_phone_b2887e_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="leads_custo_name_436f73_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["-last_contact_date"], name="leads_custo_last_co_0f42b7_idx"
            ),
        ),
    ]
