# Generated by Django 5.0.6 on 2026-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_customer_lead_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="recommendations",
            field=models.TextField(blank=True, help_text="AI or Staff recommendations"),
        ),
        migrations.AddField(
            model_name="lead",
            name="referred_by",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
