# Generated by Django 5.0.6 on 2026-05-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_lead_recommendations_lead_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
