# Generated by Django 5.0.6 on 2026-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_followup_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="status_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for closing or specific status detail",
                max_length=200,
            ),
        ),
    ]
