# Generated by Django 5.0.6 on 2026-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_followup_status_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="district",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="father_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="house_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile2",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="panchayath",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="street",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="village",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="district",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="father_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="house_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="legacy_id",
            field=models.IntegerField(
                blank=True, help_text="Original ID from products.json", null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="mobile2",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="panchayath",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="street",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="village",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
