# Generated by Django 5.0.6 on 2026-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_customer_district_customer_father_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(
                blank=True, help_text="General notes about this customer", null=True
            ),
        ),
    ]
