# Generated by Django 5.0.6 on 2026-05-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_customer_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="temperature",
            field=models.CharField(
                choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                default="cold",
                help_text="Lead priority/temperature",
                max_length=10,
            ),
        ),
    ]
