# Generated by Django 5.0.6 on 2026-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0010_customer_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="lead_type",
            field=models.CharField(
                choices=[("normal", "Normal Sale"), ("advance", "Advance Booking")],
                default="normal",
                max_length=20,
            ),
        ),
    ]
