# Generated by Django 5.0.6 on 2026-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0011_lead_lead_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="budget",
        ),
        migrations.AddField(
            model_name="lead",
            name="approx_grams",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Approximate weight in grams",
                max_digits=10,
                null=True,
            ),
        ),
    ]
