# Generated by Django 5.0.6 on 2026-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0012_remove_lead_budget_lead_approx_grams"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
