# Generated by Django 5.0.6 on 2026-05-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("no_answer", "No Answer"),
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("call_later", "Call Later"),
                            ("converted", "Converted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("next_followup_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
