# Generated by Django 5.0.6 on 2026-05-01 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calls", "0001_initial"),
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_logs",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="calllog",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["staff", "created_at"], name="calls_calll_staff_i_358dd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(fields=["lead"], name="calls_calll_lead_id_1e0584_idx"),
        ),
    ]
