# Generated by Django 5.0.6 on 2026-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="needs_field_visit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calllog",
            name="occasion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="calllog",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
