# Generated by Django 5.0.6 on 2026-05-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_calllog_needs_field_visit_calllog_occasion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calllog",
            name="priority",
        ),
    ]
