# Generated by Django 5.0.6 on 2026-05-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("field_visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldvisit",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_visits",
                to="branches.branch",
            ),
        ),
    ]
