# Generated by Django 5.0.6 on 2026-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field_visits", "0002_alter_fieldvisit_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldvisit",
            name="distance_km",
            field=models.FloatField(
                blank=True, help_text="Total distance traveled in km", null=True
            ),
        ),
        migrations.AddField(
            model_name="fieldvisit",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True, help_text="Visit duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="fieldvisit",
            name="end_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="fieldvisit",
            name="end_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fieldvisit",
            name="start_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fieldvisit",
            name="start_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
