# Generated by Django 5.0.6 on 2026-05-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field_visits", "0004_locationtracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationtracking",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
