# Generated by Django 5.0.6 on 2026-05-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field_visits", "0005_locationtracking_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldvisit",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Instructions or notes for the field staff"
            ),
        ),
        migrations.AddField(
            model_name="fieldvisit",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True, help_text="Planned date for the visit", null=True
            ),
        ),
    ]
