# Generated by Django 5.0.6 on 2026-05-04 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("center_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("center_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("radius_meters", models.IntegerField(help_text="Radius in meters")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["branch", "name"],
            },
        ),
        migrations.CreateModel(
            name="LocationBasedCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("enter", "Enter Geofence"),
                            ("exit", "Exit Geofence"),
                            ("dwell", "Dwell Time"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(help_text="WhatsApp message to send")),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0, help_text="Delay in minutes before sending"
                    ),
                ),
                (
                    "max_sends_per_day",
                    models.IntegerField(
                        default=1, help_text="Maximum sends per customer per day"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="Campaign active start time", null=True
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="Campaign active end time", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="marketing.geofence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("lng", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        help_text="Source of location data", max_length=50
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["lead", "timestamp"],
                        name="marketing_c_lead_id_f91d21_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="marketing_c_timesta_066c60_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("enter", "Enter Geofence"),
                            ("exit", "Exit Geofence"),
                            ("dwell", "Dwell Time"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "location_at_trigger",
                    models.JSONField(help_text="Location data at trigger time"),
                ),
                ("scheduled_send_time", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="marketing.locationbasedcampaign",
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="marketing.geofence",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_triggers",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "created_at"],
                        name="marketing_l_lead_id_90518c_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_send_time"],
                        name="marketing_l_status_b1f2a6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NearbyCustomerAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_meters", models.FloatField()),
                ("message_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby_alerts",
                        to="branches.branch",
                    ),
                ),
                (
                    "campaign_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketing.locationbasedcampaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby_alerts",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "created_at"],
                        name="marketing_n_branch__35cd95_idx",
                    ),
                    models.Index(
                        fields=["message_sent", "created_at"],
                        name="marketing_n_message_7613d7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProximityTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_meters", models.FloatField()),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proximity_targets",
                        to="branches.branch",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proximity_targets",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["distance_meters"],
                "indexes": [
                    models.Index(
                        fields=["branch", "is_active", "distance_meters"],
                        name="marketing_p_branch__8f4b6a_idx",
                    )
                ],
                "unique_together": {("branch", "lead")},
            },
        ),
    ]
