# Generated by Django 5.0.6 on 2026-05-01 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="join_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("field_staff", "Field Staff"),
                    ("office_staff", "Office Staff"),
                    ("telecaller", "Telecaller"),
                    ("custom", "Custom"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_type_label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner / Admin"),
                    ("manager", "Branch Manager"),
                    ("sub_manager", "Sub Manager"),
                    ("staff", "Office Staff"),
                    ("telecaller", "Telecaller"),
                    ("field_staff", "Field Staff"),
                    ("custom", "Custom Staff"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubManagerPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view_leads", models.BooleanField(default=True)),
                ("can_add_leads", models.BooleanField(default=False)),
                ("can_edit_leads", models.BooleanField(default=False)),
                ("can_assign_leads", models.BooleanField(default=False)),
                ("can_delete_leads", models.BooleanField(default=False)),
                ("can_view_staff", models.BooleanField(default=True)),
                ("can_add_staff", models.BooleanField(default=False)),
                ("can_edit_staff", models.BooleanField(default=False)),
                ("can_delete_staff", models.BooleanField(default=False)),
                ("can_view_attendance", models.BooleanField(default=True)),
                ("can_approve_attendance", models.BooleanField(default=False)),
                ("can_view_calls", models.BooleanField(default=False)),
                ("can_add_calls", models.BooleanField(default=False)),
                ("can_view_sales", models.BooleanField(default=False)),
                ("can_add_sales", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_export_reports", models.BooleanField(default=False)),
                ("can_view_campaigns", models.BooleanField(default=False)),
                ("can_create_campaigns", models.BooleanField(default=False)),
                ("can_view_field_visits", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "sub_manager"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
