# Generated by Django 5.0.6 on 2026-05-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_address_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view_leads", models.BooleanField(default=True)),
                ("can_add_leads", models.BooleanField(default=False)),
                ("can_edit_leads", models.BooleanField(default=False)),
                ("can_assign_leads", models.BooleanField(default=False)),
                ("can_delete_leads", models.BooleanField(default=False)),
                ("can_view_staff", models.BooleanField(default=True)),
                ("can_add_staff", models.BooleanField(default=False)),
                ("can_edit_staff", models.BooleanField(default=False)),
                ("can_delete_staff", models.BooleanField(default=False)),
                ("can_view_attendance", models.BooleanField(default=True)),
                ("can_approve_attendance", models.BooleanField(default=False)),
                ("can_view_calls", models.BooleanField(default=False)),
                ("can_add_calls", models.BooleanField(default=False)),
                ("can_view_sales", models.BooleanField(default=False)),
                ("can_add_sales", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_export_reports", models.BooleanField(default=False)),
                ("can_view_campaigns", models.BooleanField(default=False)),
                ("can_create_campaigns", models.BooleanField(default=False)),
                ("can_view_field_visits", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SubManagerPermission",
        ),
    ]
