# Generated by Django 5.0.6 on 2026-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_staffpermission_delete_submanagerpermission"),
        ("branches", "0002_alter_company_options_alter_segment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expert_segments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Segments this staff member specializes in",
                related_name="expert_staff",
                to="branches.segment",
            ),
        ),
    ]
