# Generated by Django 5.0.6 on 2026-05-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"], "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="segment",
            options={"ordering": ["id"]},
        ),
    ]
