# Generated by Django 5.0.6 on 2026-05-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_leads", models.IntegerField(default=0)),
                ("total_calls", models.IntegerField(default=0)),
                ("total_sales", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("branch", "date")},
            },
        ),
    ]
