# Generated by Django 5.0.6 on 2026-05-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("monthly", "Monthly"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("data", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["branch", "period", "date"],
                        name="reports_rep_branch__c22021_idx",
                    )
                ],
            },
        ),
    ]
