# Generated by Django 5.0.6 on 2026-05-04 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("reports", "0002_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional log data"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="system",
                        help_text="What triggered this generation",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(help_text="Time to generate the report"),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of week (0=Monday, 6=Sunday)",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, help_text="Day of month", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["frequency", "time_of_day"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("daily_eod", "Daily EOD Report"),
                            ("weekly_summary", "Weekly Summary"),
                            ("monthly_performance", "Monthly Performance"),
                            ("sales_analysis", "Sales Analysis"),
                            ("lead_analysis", "Lead Analysis"),
                            ("staff_performance", "Staff Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "content_template",
                    models.TextField(
                        help_text="Template with placeholders for dynamic content"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_generate",
                    models.BooleanField(
                        default=True, help_text="Auto-generate this report"
                    ),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for scheduling",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="attendance_present",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="attendance_rate",
            field=models.FloatField(
                default=0.0, help_text="Staff attendance rate percentage"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="attendance_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="call_connect_rate",
            field=models.FloatField(
                default=0.0, help_text="Call connection rate percentage"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="calls_connected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="conversion_rate",
            field=models.FloatField(
                default=0.0, help_text="Lead conversion rate percentage"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="leads_converted",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="sent_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="daily_reports_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error if report generation failed"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="recipients",
            field=models.ManyToManyField(
                blank=True, related_name="received_reports", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When report was sent to recipients", null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="generating",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="data",
            field=models.JSONField(default=dict, help_text="Comprehensive report data"),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("branch", "period", "date")},
        ),
        migrations.AddIndex(
            model_name="dailyreport",
            index=models.Index(
                fields=["branch", "date", "status"],
                name="reports_dai_branch__18a1a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "date"], name="reports_rep_status_a02fc6_idx"
            ),
        ),
        migrations.AddField(
            model_name="reportlog",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="reports.report",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_report_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="recipients",
            field=models.ManyToManyField(
                blank=True, related_name="report_templates", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="reports.reporttemplate",
            ),
        ),
        migrations.AddField(
            model_name="reportlog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="reports.reporttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="reportlog",
            index=models.Index(
                fields=["status", "started_at"], name="reports_rep_status_272c94_idx"
            ),
        ),
    ]
