# Generated by Django 5.0.6 on 2026-05-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_reportlog_reportschedule_reporttemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="total_weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
