# Generated by Django 5.0.6 on 2026-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_dailyreport_total_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="weight_by_segment",
            field=models.JSONField(
                blank=True, default=dict, help_text="Breakdown of weight by segment"
            ),
        ),
    ]
