# Generated by Django 5.0.6 on 2026-05-04 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("performance", "Performance"),
                            ("activity", "Activity"),
                            ("deadline", "Deadline"),
                            ("opportunity", "Opportunity"),
                            ("risk", "Risk"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "template_message",
                    models.TextField(
                        help_text="Template for alert message with placeholders"
                    ),
                ),
                ("default_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "severity", "name"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("sales_count", "Sales Count"),
                            ("sales_revenue", "Sales Revenue"),
                            ("leads_count", "Leads Count"),
                            ("leads_converted", "Leads Converted"),
                            ("calls_made", "Calls Made"),
                            ("conversion_rate", "Conversion Rate"),
                            ("attendance_rate", "Attendance Rate"),
                            ("response_time", "Response Time"),
                            ("followup_overdue", "Overdue Follow-ups"),
                            ("inventory_low", "Low Inventory"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("eq", "Equal To"),
                            ("gte", "Greater Than or Equal"),
                            ("lte", "Less Than or Equal"),
                            ("contains", "Contains"),
                            ("not_contains", "Does Not Contain"),
                            ("is_null", "Is Null"),
                            ("is_not_null", "Is Not Null"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("threshold_text", models.CharField(blank=True, max_length=200)),
                (
                    "time_period_hours",
                    models.IntegerField(
                        default=24, help_text="Time period in hours to check"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target_roles",
                    models.JSONField(
                        default=list, help_text="Roles that should receive this alert"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alert_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="alerts.alerttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("leads", "Leads"),
                            ("marketing", "Marketing"),
                            ("operations", "Operations"),
                            ("performance", "Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "recommendation",
                    models.TextField(help_text="Specific action to take"),
                ),
                (
                    "expected_impact",
                    models.TextField(
                        blank=True,
                        help_text="Expected outcome if suggestion is followed",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="AI confidence score (0-1)"),
                ),
                (
                    "data_insights",
                    models.JSONField(help_text="Data that led to this suggestion"),
                ),
                ("is_implemented", models.BooleanField(default=False)),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback_score",
                    models.IntegerField(
                        blank=True, help_text="User feedback 1-5", null=True
                    ),
                ),
                ("feedback_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "implemented_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implemented_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        related_name="suggestions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("digest_date", models.DateField()),
                ("alert_count", models.IntegerField(default=0)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-digest_date", "user"],
                "unique_together": {("user", "period", "digest_date")},
            },
        ),
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_subscribed", models.BooleanField(default=True)),
                (
                    "notification_channels",
                    models.JSONField(
                        default=dict,
                        help_text="Channels: {'in_app': true, 'email': false, 'whatsapp': false}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alert_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="alerts.alerttype",
                    ),
                ),
            ],
            options={
                "ordering": ["user", "alert_type"],
                "unique_together": {("user", "alert_type")},
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("severity", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional alert data"),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="received_alerts", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="alerts.alertrule",
                    ),
                ),
                (
                    "alert_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="alerts.alerttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "triggered_at"],
                        name="alerts_aler_status_aeb1a9_idx",
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="alerts_aler_severit_12d0e1_idx",
                    ),
                ],
            },
        ),
    ]
