# Generated by Django 5.0.6 on 2026-05-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignlead",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_entries",
                to="leads.lead",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignlead",
            unique_together={("campaign", "lead")},
        ),
    ]
