# Generated by Django 5.0.6 on 2026-05-01 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("campaigns", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignlead",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AddField(
            model_name="campaign",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignlead",
            name="error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="campaignlead",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("festival", "Festival Offer"),
                    ("bridal", "Bridal Campaign"),
                    ("gold_rate", "Gold Rate Alert"),
                    ("recovery", "Lost Lead Recovery"),
                    ("followup", "Follow-up Reminder"),
                    ("birthday", "Birthday Wish"),
                    ("anniversary", "Work Anniversary"),
                    ("special_day", "Special Day"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="branches.segment",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("active", "Active"),
                    ("sent", "Sent"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="template_name",
            field=models.CharField(
                blank=True,
                help_text="Meta pre-approved WhatsApp template name (overrides whatsapp_template)",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="SpecialDayMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Onam, Christmas, Eid", max_length=100
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date this message fires every year"),
                ),
                (
                    "message",
                    models.TextField(help_text="Placeholders: {name}, {branch}"),
                ),
                (
                    "send_to_staff",
                    models.BooleanField(
                        default=True, help_text="Send to all active staff"
                    ),
                ),
                (
                    "send_to_leads",
                    models.BooleanField(
                        default=False, help_text="Send to active leads"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="special_day_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday Wish"),
                            ("anniversary", "Work Anniversary"),
                            ("special_day", "Special Day / Festival"),
                            ("campaign", "Campaign Blast"),
                            ("manual", "Manual / On-demand"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Placeholders: {name}, {date}, {branch}, {role}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["trigger", "name"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="whatsapp_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Reusable template with placeholders",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="campaigns.whatsapptemplate",
            ),
        ),
    ]
