# Generated by Django 5.0.6 on 2026-05-06 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_branch_manager"),
        ("campaigns", "0003_alter_campaignlead_options_campaign_sent_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("google_analytics", "Google Analytics"),
                            ("google_ads", "Google Ads"),
                            ("facebook_ads", "Facebook Ads"),
                            ("instagram_insights", "Instagram Insights"),
                            ("youtube_analytics", "YouTube Analytics"),
                            ("whatsapp_business", "WhatsApp Business Analytics"),
                            ("mailchimp", "Mailchimp"),
                            ("brevo", "Brevo"),
                            ("sendgrid", "SendGrid"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for the connected account",
                        max_length=200,
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True,
                        help_text="Platform-specific account ID",
                        max_length=200,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, help_text="Encrypted OAuth access token"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, help_text="Encrypted OAuth refresh token"
                    ),
                ),
                (
                    "token_expiry",
                    models.DateTimeField(
                        blank=True, help_text="Token expiration time", null=True
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable automatic analytics syncing"
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("syncing", "Syncing"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, help_text="Last sync error message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch-specific integration (null = global)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "ordering": ["platform"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the analytics data")),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("engagement", models.BigIntegerField(default=0)),
                ("reach", models.BigIntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("leads", models.IntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("video_views", models.BigIntegerField(default=0)),
                (
                    "roi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Return on Investment %",
                        max_digits=8,
                    ),
                ),
                (
                    "roas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Return on Ad Spend",
                        max_digits=8,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw API response for debugging",
                        null=True,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="campaigns.integration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Analytics",
                "verbose_name_plural": "Integration Analytics",
                "ordering": ["-date"],
                "unique_together": {("integration", "date")},
            },
        ),
    ]
