# Generated by Django 5.0.6 on 2026-05-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_branch_manager"),
        ("campaigns", "0004_integration_integrationanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra configuration and platform-specific IDs",
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="platform",
            field=models.CharField(
                choices=[
                    ("google_analytics", "Google Analytics"),
                    ("google_ads", "Google Ads"),
                    ("facebook_ads", "Facebook Ads"),
                    ("instagram_insights", "Instagram Insights"),
                    ("youtube_analytics", "YouTube Analytics"),
                    ("whatsapp_business", "WhatsApp Business Analytics"),
                    ("mailchimp", "Mailchimp"),
                    ("brevo", "Brevo"),
                    ("sendgrid", "SendGrid"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integration",
            unique_together={("platform", "branch")},
        ),
    ]
