# Generated by Django 5.0.6 on 2026-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_integration_metadata_alter_integration_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("organic", "Organic"),
                    ("offline", "Offline"),
                    ("event", "Event"),
                ],
                default="organic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="objective",
            field=models.CharField(
                choices=[
                    ("awareness", "Awareness"),
                    ("engagement", "Engagement"),
                    ("lead_generation", "Lead Generation"),
                    ("sales", "Sales"),
                    ("retention", "Retention"),
                    ("branding", "Branding"),
                ],
                default="awareness",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="platforms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of platforms like facebook_ads, instagram",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of tags like festival, wedding, whatsapp",
            ),
        ),
    ]
