# Generated by Django 5.0.6 on 2026-05-12 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="notifications/"),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_broadcast",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("followup", "Follow-up Reminder"),
                    ("hot_lead", "Hot Lead Alert"),
                    ("attendance", "Attendance Approval"),
                    ("campaign", "Campaign Update"),
                    ("announcement", "Announcement"),
                    ("birthday", "Birthday Wish"),
                    ("anniversary", "Work Anniversary"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
