# Generated by Django 5.0.6 on 2026-05-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_branch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="checked_in_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_type",
            field=models.CharField(
                choices=[
                    ("gps", "GPS Check-in"),
                    ("manual", "Manual Check-in"),
                    ("photo", "Photo Check-in"),
                ],
                default="gps",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="distance_from_branch",
            field=models.FloatField(
                blank=True,
                help_text="Distance in meters from branch location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                    ("pending", "Pending Approval"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
