# Generated by Django 5.0.6 on 2026-05-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0004_attendance_check_out_lat_attendance_check_out_lng_and_more",
        ),
        ("branches", "0003_branch_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Morning Shift, Afternoon Shift", max_length=50
                    ),
                ),
                ("check_in_time", models.TimeField()),
                ("check_out_time", models.TimeField()),
                ("grace_period_minutes", models.IntegerField(default=15)),
                (
                    "reminder_slots",
                    models.JSONField(
                        default=list,
                        help_text="List of times (HH:MM) to trigger automated attendance requests. Example: ['09:30', '09:40', '09:55']",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_schedules",
                        to="branches.branch",
                    ),
                ),
            ],
        ),
    ]
