# Generated by Django 5.0.6 on 2026-05-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="product_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
