# Generated by Django 5.0.6 on 2026-05-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_sale_branch_alter_sale_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sale_type",
            field=models.CharField(
                choices=[("normal", "Normal Sale"), ("advance", "Advance Booking")],
                default="normal",
                max_length=20,
            ),
        ),
    ]
