# Generated by Django 5.0.6 on 2026-05-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sale_sale_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
